// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/player.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiPlayerInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 1207301419;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'lplayer_core',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiPlayerLPlayerAddSubtitle({
    required LPlayer that,
    required String path,
  });

  Stream<PlayerEvent> crateApiPlayerLPlayerEvents({required LPlayer that});

  Future<void> crateApiPlayerLPlayerOpen({
    required LPlayer that,
    required String uri,
    required List<String> subtitles,
  });

  Future<void> crateApiPlayerLPlayerPause({required LPlayer that});

  Future<void> crateApiPlayerLPlayerPlay({required LPlayer that});

  Future<void> crateApiPlayerLPlayerSeekBy({
    required LPlayer that,
    required double seconds,
  });

  Future<void> crateApiPlayerLPlayerSeekTo({
    required LPlayer that,
    required double seconds,
  });

  Future<void> crateApiPlayerLPlayerSelectAudioTrack({
    required LPlayer that,
    int? id,
  });

  Future<void> crateApiPlayerLPlayerSelectSubtitleTrack({
    required LPlayer that,
    int? id,
  });

  Future<void> crateApiPlayerLPlayerSetMuted({
    required LPlayer that,
    required bool muted,
  });

  Future<void> crateApiPlayerLPlayerSetSpeed({
    required LPlayer that,
    required double speed,
  });

  Future<void> crateApiPlayerLPlayerSetSubtitlesVisible({
    required LPlayer that,
    required bool visible,
  });

  Future<void> crateApiPlayerLPlayerSetVolume({
    required LPlayer that,
    required double volume,
  });

  Future<void> crateApiPlayerLPlayerStop({required LPlayer that});

  PlatformInt64 crateApiPlayerLPlayerTextureId({required LPlayer that});

  Future<void> crateApiPlayerLPlayerTogglePause({required LPlayer that});

  Future<LPlayer> crateApiPlayerCreatePlayer({
    required PlatformInt64 engineHandle,
  });

  Future<void> crateApiPlayerInitApp();

  Future<PlayerState> crateApiPlayerPlayerStateDefault();

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_LPlayer;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_LPlayer;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_LPlayerPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiPlayerLPlayerAddSubtitle({
    required LPlayer that,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLPlayer(
            that,
            serializer,
          );
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerLPlayerAddSubtitleConstMeta,
        argValues: [that, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerLPlayerAddSubtitleConstMeta =>
      const TaskConstMeta(
        debugName: "LPlayer_add_subtitle",
        argNames: ["that", "path"],
      );

  @override
  Stream<PlayerEvent> crateApiPlayerLPlayerEvents({required LPlayer that}) {
    final sink = RustStreamSink<PlayerEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLPlayer(
              that,
              serializer,
            );
            sse_encode_StreamSink_player_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 2,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiPlayerLPlayerEventsConstMeta,
          argValues: [that, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiPlayerLPlayerEventsConstMeta =>
      const TaskConstMeta(
        debugName: "LPlayer_events",
        argNames: ["that", "sink"],
      );

  @override
  Future<void> crateApiPlayerLPlayerOpen({
    required LPlayer that,
    required String uri,
    required List<String> subtitles,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLPlayer(
            that,
            serializer,
          );
          sse_encode_String(uri, serializer);
          sse_encode_list_String(subtitles, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerLPlayerOpenConstMeta,
        argValues: [that, uri, subtitles],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerLPlayerOpenConstMeta => const TaskConstMeta(
    debugName: "LPlayer_open",
    argNames: ["that", "uri", "subtitles"],
  );

  @override
  Future<void> crateApiPlayerLPlayerPause({required LPlayer that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLPlayer(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerLPlayerPauseConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerLPlayerPauseConstMeta =>
      const TaskConstMeta(debugName: "LPlayer_pause", argNames: ["that"]);

  @override
  Future<void> crateApiPlayerLPlayerPlay({required LPlayer that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLPlayer(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerLPlayerPlayConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerLPlayerPlayConstMeta =>
      const TaskConstMeta(debugName: "LPlayer_play", argNames: ["that"]);

  @override
  Future<void> crateApiPlayerLPlayerSeekBy({
    required LPlayer that,
    required double seconds,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLPlayer(
            that,
            serializer,
          );
          sse_encode_f_64(seconds, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerLPlayerSeekByConstMeta,
        argValues: [that, seconds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerLPlayerSeekByConstMeta =>
      const TaskConstMeta(
        debugName: "LPlayer_seek_by",
        argNames: ["that", "seconds"],
      );

  @override
  Future<void> crateApiPlayerLPlayerSeekTo({
    required LPlayer that,
    required double seconds,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLPlayer(
            that,
            serializer,
          );
          sse_encode_f_64(seconds, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerLPlayerSeekToConstMeta,
        argValues: [that, seconds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerLPlayerSeekToConstMeta =>
      const TaskConstMeta(
        debugName: "LPlayer_seek_to",
        argNames: ["that", "seconds"],
      );

  @override
  Future<void> crateApiPlayerLPlayerSelectAudioTrack({
    required LPlayer that,
    int? id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLPlayer(
            that,
            serializer,
          );
          sse_encode_opt_box_autoadd_i_32(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerLPlayerSelectAudioTrackConstMeta,
        argValues: [that, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerLPlayerSelectAudioTrackConstMeta =>
      const TaskConstMeta(
        debugName: "LPlayer_select_audio_track",
        argNames: ["that", "id"],
      );

  @override
  Future<void> crateApiPlayerLPlayerSelectSubtitleTrack({
    required LPlayer that,
    int? id,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLPlayer(
            that,
            serializer,
          );
          sse_encode_opt_box_autoadd_i_32(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerLPlayerSelectSubtitleTrackConstMeta,
        argValues: [that, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerLPlayerSelectSubtitleTrackConstMeta =>
      const TaskConstMeta(
        debugName: "LPlayer_select_subtitle_track",
        argNames: ["that", "id"],
      );

  @override
  Future<void> crateApiPlayerLPlayerSetMuted({
    required LPlayer that,
    required bool muted,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLPlayer(
            that,
            serializer,
          );
          sse_encode_bool(muted, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerLPlayerSetMutedConstMeta,
        argValues: [that, muted],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerLPlayerSetMutedConstMeta =>
      const TaskConstMeta(
        debugName: "LPlayer_set_muted",
        argNames: ["that", "muted"],
      );

  @override
  Future<void> crateApiPlayerLPlayerSetSpeed({
    required LPlayer that,
    required double speed,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLPlayer(
            that,
            serializer,
          );
          sse_encode_f_64(speed, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerLPlayerSetSpeedConstMeta,
        argValues: [that, speed],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerLPlayerSetSpeedConstMeta =>
      const TaskConstMeta(
        debugName: "LPlayer_set_speed",
        argNames: ["that", "speed"],
      );

  @override
  Future<void> crateApiPlayerLPlayerSetSubtitlesVisible({
    required LPlayer that,
    required bool visible,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLPlayer(
            that,
            serializer,
          );
          sse_encode_bool(visible, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerLPlayerSetSubtitlesVisibleConstMeta,
        argValues: [that, visible],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerLPlayerSetSubtitlesVisibleConstMeta =>
      const TaskConstMeta(
        debugName: "LPlayer_set_subtitles_visible",
        argNames: ["that", "visible"],
      );

  @override
  Future<void> crateApiPlayerLPlayerSetVolume({
    required LPlayer that,
    required double volume,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLPlayer(
            that,
            serializer,
          );
          sse_encode_f_64(volume, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerLPlayerSetVolumeConstMeta,
        argValues: [that, volume],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerLPlayerSetVolumeConstMeta =>
      const TaskConstMeta(
        debugName: "LPlayer_set_volume",
        argNames: ["that", "volume"],
      );

  @override
  Future<void> crateApiPlayerLPlayerStop({required LPlayer that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLPlayer(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerLPlayerStopConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerLPlayerStopConstMeta =>
      const TaskConstMeta(debugName: "LPlayer_stop", argNames: ["that"]);

  @override
  PlatformInt64 crateApiPlayerLPlayerTextureId({required LPlayer that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLPlayer(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPlayerLPlayerTextureIdConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerLPlayerTextureIdConstMeta =>
      const TaskConstMeta(debugName: "LPlayer_texture_id", argNames: ["that"]);

  @override
  Future<void> crateApiPlayerLPlayerTogglePause({required LPlayer that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLPlayer(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerLPlayerTogglePauseConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerLPlayerTogglePauseConstMeta =>
      const TaskConstMeta(
        debugName: "LPlayer_toggle_pause",
        argNames: ["that"],
      );

  @override
  Future<LPlayer> crateApiPlayerCreatePlayer({
    required PlatformInt64 engineHandle,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(engineHandle, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLPlayer,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiPlayerCreatePlayerConstMeta,
        argValues: [engineHandle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerCreatePlayerConstMeta => const TaskConstMeta(
    debugName: "create_player",
    argNames: ["engineHandle"],
  );

  @override
  Future<void> crateApiPlayerInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPlayerInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<PlayerState> crateApiPlayerPlayerStateDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_player_state,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPlayerPlayerStateDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerStateDefaultConstMeta =>
      const TaskConstMeta(debugName: "player_state_default", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_LPlayer => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLPlayer;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_LPlayer => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLPlayer;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  LPlayer
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLPlayer(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LPlayerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LPlayer
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLPlayer(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LPlayerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  LPlayer
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLPlayer(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LPlayerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<PlayerEvent> dco_decode_StreamSink_player_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<MediaTrack> dco_decode_list_media_track(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_media_track).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MediaTrack dco_decode_media_track(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return MediaTrack(
      id: dco_decode_i_32(arr[0]),
      kind: dco_decode_track_kind(arr[1]),
      title: dco_decode_opt_String(arr[2]),
      language: dco_decode_opt_String(arr[3]),
      codec: dco_decode_opt_String(arr[4]),
      selected: dco_decode_bool(arr[5]),
      externalFilename: dco_decode_opt_String(arr[6]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  PlayerEvent dco_decode_player_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return PlayerEvent(
      kind: dco_decode_player_event_kind(arr[0]),
      state: dco_decode_player_state(arr[1]),
      message: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  PlayerEventKind dco_decode_player_event_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PlayerEventKind.values[raw as int];
  }

  @protected
  PlayerState dco_decode_player_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 13)
      throw Exception('unexpected arr length: expect 13 but see ${arr.length}');
    return PlayerState(
      position: dco_decode_f_64(arr[0]),
      duration: dco_decode_f_64(arr[1]),
      paused: dco_decode_bool(arr[2]),
      idle: dco_decode_bool(arr[3]),
      buffering: dco_decode_bool(arr[4]),
      volume: dco_decode_f_64(arr[5]),
      muted: dco_decode_bool(arr[6]),
      speed: dco_decode_f_64(arr[7]),
      subtitlesVisible: dco_decode_bool(arr[8]),
      videoWidth: dco_decode_i_32(arr[9]),
      videoHeight: dco_decode_i_32(arr[10]),
      title: dco_decode_String(arr[11]),
      tracks: dco_decode_list_media_track(arr[12]),
    );
  }

  @protected
  TrackKind dco_decode_track_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TrackKind.values[raw as int];
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  LPlayer
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLPlayer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LPlayerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  LPlayer
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLPlayer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LPlayerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  LPlayer
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLPlayer(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LPlayerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<PlayerEvent> sse_decode_StreamSink_player_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<MediaTrack> sse_decode_list_media_track(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MediaTrack>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_media_track(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MediaTrack sse_decode_media_track(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_32(deserializer);
    var var_kind = sse_decode_track_kind(deserializer);
    var var_title = sse_decode_opt_String(deserializer);
    var var_language = sse_decode_opt_String(deserializer);
    var var_codec = sse_decode_opt_String(deserializer);
    var var_selected = sse_decode_bool(deserializer);
    var var_externalFilename = sse_decode_opt_String(deserializer);
    return MediaTrack(
      id: var_id,
      kind: var_kind,
      title: var_title,
      language: var_language,
      codec: var_codec,
      selected: var_selected,
      externalFilename: var_externalFilename,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlayerEvent sse_decode_player_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_player_event_kind(deserializer);
    var var_state = sse_decode_player_state(deserializer);
    var var_message = sse_decode_opt_String(deserializer);
    return PlayerEvent(kind: var_kind, state: var_state, message: var_message);
  }

  @protected
  PlayerEventKind sse_decode_player_event_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return PlayerEventKind.values[inner];
  }

  @protected
  PlayerState sse_decode_player_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_position = sse_decode_f_64(deserializer);
    var var_duration = sse_decode_f_64(deserializer);
    var var_paused = sse_decode_bool(deserializer);
    var var_idle = sse_decode_bool(deserializer);
    var var_buffering = sse_decode_bool(deserializer);
    var var_volume = sse_decode_f_64(deserializer);
    var var_muted = sse_decode_bool(deserializer);
    var var_speed = sse_decode_f_64(deserializer);
    var var_subtitlesVisible = sse_decode_bool(deserializer);
    var var_videoWidth = sse_decode_i_32(deserializer);
    var var_videoHeight = sse_decode_i_32(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_tracks = sse_decode_list_media_track(deserializer);
    return PlayerState(
      position: var_position,
      duration: var_duration,
      paused: var_paused,
      idle: var_idle,
      buffering: var_buffering,
      volume: var_volume,
      muted: var_muted,
      speed: var_speed,
      subtitlesVisible: var_subtitlesVisible,
      videoWidth: var_videoWidth,
      videoHeight: var_videoHeight,
      title: var_title,
      tracks: var_tracks,
    );
  }

  @protected
  TrackKind sse_decode_track_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return TrackKind.values[inner];
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLPlayer(
    LPlayer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LPlayerImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLPlayer(
    LPlayer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LPlayerImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLPlayer(
    LPlayer self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LPlayerImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_player_event_Sse(
    RustStreamSink<PlayerEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_player_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_media_track(
    List<MediaTrack> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_media_track(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_media_track(MediaTrack self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.id, serializer);
    sse_encode_track_kind(self.kind, serializer);
    sse_encode_opt_String(self.title, serializer);
    sse_encode_opt_String(self.language, serializer);
    sse_encode_opt_String(self.codec, serializer);
    sse_encode_bool(self.selected, serializer);
    sse_encode_opt_String(self.externalFilename, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_player_event(PlayerEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_player_event_kind(self.kind, serializer);
    sse_encode_player_state(self.state, serializer);
    sse_encode_opt_String(self.message, serializer);
  }

  @protected
  void sse_encode_player_event_kind(
    PlayerEventKind self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_player_state(PlayerState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.position, serializer);
    sse_encode_f_64(self.duration, serializer);
    sse_encode_bool(self.paused, serializer);
    sse_encode_bool(self.idle, serializer);
    sse_encode_bool(self.buffering, serializer);
    sse_encode_f_64(self.volume, serializer);
    sse_encode_bool(self.muted, serializer);
    sse_encode_f_64(self.speed, serializer);
    sse_encode_bool(self.subtitlesVisible, serializer);
    sse_encode_i_32(self.videoWidth, serializer);
    sse_encode_i_32(self.videoHeight, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_list_media_track(self.tracks, serializer);
  }

  @protected
  void sse_encode_track_kind(TrackKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class LPlayerImpl extends RustOpaque implements LPlayer {
  // Not to be used by end users
  LPlayerImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  LPlayerImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_LPlayer,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_LPlayer,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_LPlayerPtr,
  );

  /// Adds an external subtitle to the current file (or to the file that is
  /// being loaded right now) and selects it.
  Future<void> addSubtitle({required String path}) => RustLib.instance.api
      .crateApiPlayerLPlayerAddSubtitle(that: this, path: path);

  /// Stream of playback events. Emits the current state right away.
  Stream<PlayerEvent> events() =>
      RustLib.instance.api.crateApiPlayerLPlayerEvents(that: this);

  /// Plays a local file or URL, replacing whatever is playing now.
  /// `subtitles` are external subtitle files added once the file is loaded.
  Future<void> open({required String uri, required List<String> subtitles}) =>
      RustLib.instance.api.crateApiPlayerLPlayerOpen(
        that: this,
        uri: uri,
        subtitles: subtitles,
      );

  Future<void> pause() =>
      RustLib.instance.api.crateApiPlayerLPlayerPause(that: this);

  Future<void> play() =>
      RustLib.instance.api.crateApiPlayerLPlayerPlay(that: this);

  /// Seeks relative to the current position, negative goes backward.
  /// Uses exact seeking so small steps like 0.5s are honored.
  Future<void> seekBy({required double seconds}) => RustLib.instance.api
      .crateApiPlayerLPlayerSeekBy(that: this, seconds: seconds);

  /// Seeks to an absolute position in seconds.
  Future<void> seekTo({required double seconds}) => RustLib.instance.api
      .crateApiPlayerLPlayerSeekTo(that: this, seconds: seconds);

  /// Selects an audio track by id, None turns audio off.
  Future<void> selectAudioTrack({int? id}) => RustLib.instance.api
      .crateApiPlayerLPlayerSelectAudioTrack(that: this, id: id);

  /// Selects a subtitle track by id, None turns subtitles off.
  Future<void> selectSubtitleTrack({int? id}) => RustLib.instance.api
      .crateApiPlayerLPlayerSelectSubtitleTrack(that: this, id: id);

  /// Playback speed, 1.0 is normal.
  /// Mutes audio without touching the volume.
  Future<void> setMuted({required bool muted}) => RustLib.instance.api
      .crateApiPlayerLPlayerSetMuted(that: this, muted: muted);

  Future<void> setSpeed({required double speed}) => RustLib.instance.api
      .crateApiPlayerLPlayerSetSpeed(that: this, speed: speed);

  Future<void> setSubtitlesVisible({required bool visible}) => RustLib
      .instance
      .api
      .crateApiPlayerLPlayerSetSubtitlesVisible(that: this, visible: visible);

  /// Volume in 0..=100.
  Future<void> setVolume({required double volume}) => RustLib.instance.api
      .crateApiPlayerLPlayerSetVolume(that: this, volume: volume);

  Future<void> stop() =>
      RustLib.instance.api.crateApiPlayerLPlayerStop(that: this);

  /// Id for Flutter's `Texture(textureId: ...)` widget.
  PlatformInt64 get textureId =>
      RustLib.instance.api.crateApiPlayerLPlayerTextureId(that: this);

  Future<void> togglePause() =>
      RustLib.instance.api.crateApiPlayerLPlayerTogglePause(that: this);
}
