// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_property`, `command`, `emit`, `event_loop`, `get_string`, `new`, `prop_double`, `prop_flag`, `prop_int64`, `prop_string`, `refresh_tracks`, `set_double`, `set_flag`, `set_option`, `set_string`, `track_value`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Inner`, `Mpv`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `drop`, `drop`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Creates the player and its video texture. `engine_handle` comes from
/// `EngineContext.instance.getEngineHandle()` on the Dart side.
Future<LPlayer> createPlayer({required PlatformInt64 engineHandle}) =>
    RustLib.instance.api.crateApiPlayerCreatePlayer(engineHandle: engineHandle);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LPlayer>>
abstract class LPlayer implements RustOpaqueInterface {
  /// Adds an external subtitle to the current file (or to the file that is
  /// being loaded right now) and selects it.
  Future<void> addSubtitle({required String path});

  /// Stream of playback events. Emits the current state right away.
  Stream<PlayerEvent> events();

  /// Plays a local file or URL, replacing whatever is playing now.
  /// `subtitles` are external subtitle files added once the file is loaded.
  Future<void> open({required String uri, required List<String> subtitles});

  Future<void> pause();

  Future<void> play();

  /// Seeks relative to the current position, negative goes backward.
  /// Uses exact seeking so small steps like 0.5s are honored.
  Future<void> seekBy({required double seconds});

  /// Seeks to an absolute position in seconds.
  Future<void> seekTo({required double seconds});

  /// Selects an audio track by id, None turns audio off.
  Future<void> selectAudioTrack({int? id});

  /// Selects a subtitle track by id, None turns subtitles off.
  Future<void> selectSubtitleTrack({int? id});

  /// Playback speed, 1.0 is normal.
  /// Mutes audio without touching the volume.
  Future<void> setMuted({required bool muted});

  Future<void> setSpeed({required double speed});

  Future<void> setSubtitlesVisible({required bool visible});

  /// Volume in 0..=100.
  Future<void> setVolume({required double volume});

  Future<void> stop();

  /// Id for Flutter's `Texture(textureId: ...)` widget.
  PlatformInt64 get textureId;

  Future<void> togglePause();
}

class MediaTrack {
  /// mpv track id, unique per kind. Pass it to `select_audio_track` or
  /// `select_subtitle_track`.
  final int id;
  final TrackKind kind;
  final String? title;

  /// Language code, e.g. "eng" or "jpn".
  final String? language;
  final String? codec;
  final bool selected;

  /// Path of an external subtitle/audio file, None for embedded tracks.
  final String? externalFilename;

  const MediaTrack({
    required this.id,
    required this.kind,
    this.title,
    this.language,
    this.codec,
    required this.selected,
    this.externalFilename,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      kind.hashCode ^
      title.hashCode ^
      language.hashCode ^
      codec.hashCode ^
      selected.hashCode ^
      externalFilename.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MediaTrack &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          kind == other.kind &&
          title == other.title &&
          language == other.language &&
          codec == other.codec &&
          selected == other.selected &&
          externalFilename == other.externalFilename;
}

class PlayerEvent {
  final PlayerEventKind kind;
  final PlayerState state;
  final String? message;

  const PlayerEvent({required this.kind, required this.state, this.message});

  @override
  int get hashCode => kind.hashCode ^ state.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlayerEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          state == other.state &&
          message == other.message;
}

enum PlayerEventKind {
  stateChanged,
  fileLoaded,

  /// The current file played until the end, the UI should advance the playlist.
  endOfFile,

  /// The current file failed to load or play, `message` has the reason.
  error,
}

/// Snapshot of everything the UI needs to draw the player.
class PlayerState {
  /// Current position in seconds.
  final double position;

  /// Duration in seconds, 0 when unknown (e.g. live streams).
  final double duration;
  final bool paused;

  /// True when nothing is loaded (initial state, after stop or end of file).
  final bool idle;

  /// True while a network stream is waiting for data.
  final bool buffering;

  /// 0..=100, kept while muted so unmuting restores it.
  final double volume;
  final bool muted;
  final double speed;
  final bool subtitlesVisible;

  /// Display size of the video, 0 for audio only files.
  final int videoWidth;
  final int videoHeight;
  final String title;

  /// Audio, video and subtitle tracks of the current file.
  final List<MediaTrack> tracks;

  const PlayerState({
    required this.position,
    required this.duration,
    required this.paused,
    required this.idle,
    required this.buffering,
    required this.volume,
    required this.muted,
    required this.speed,
    required this.subtitlesVisible,
    required this.videoWidth,
    required this.videoHeight,
    required this.title,
    required this.tracks,
  });

  static Future<PlayerState> default_() =>
      RustLib.instance.api.crateApiPlayerPlayerStateDefault();

  @override
  int get hashCode =>
      position.hashCode ^
      duration.hashCode ^
      paused.hashCode ^
      idle.hashCode ^
      buffering.hashCode ^
      volume.hashCode ^
      muted.hashCode ^
      speed.hashCode ^
      subtitlesVisible.hashCode ^
      videoWidth.hashCode ^
      videoHeight.hashCode ^
      title.hashCode ^
      tracks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlayerState &&
          runtimeType == other.runtimeType &&
          position == other.position &&
          duration == other.duration &&
          paused == other.paused &&
          idle == other.idle &&
          buffering == other.buffering &&
          volume == other.volume &&
          muted == other.muted &&
          speed == other.speed &&
          subtitlesVisible == other.subtitlesVisible &&
          videoWidth == other.videoWidth &&
          videoHeight == other.videoHeight &&
          title == other.title &&
          tracks == other.tracks;
}

enum TrackKind { video, audio, subtitle }
